Revert "bump runtime"
It doesn't compile with the newer runtime :(

[445/753] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
FAILED: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
/usr/bin/ccache /usr/bin/c++ -DCVAPI_EXPORTS -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/run/build/opencv/_flatpak_build -I/run/build/opencv/modules/videoio/include -I/run/build/opencv/_flatpak_build/modules/videoio -I/run/build/opencv/modules/core/include -I/run/build/opencv/modules/imgproc/include -I/run/build/opencv/modules/imgcodecs/include -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/orc-0.4 -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-declarations -O2 -g -DNDEBUG -fPIC -MD -MT modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o -MF modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o.d -o modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o -c /run/build/opencv/modules/videoio/src/cap_ffmpeg.cpp
In file included from /run/build/opencv/modules/videoio/src/cap_ffmpeg.cpp:49:
/run/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:551:5: error: ‘AVBSFContext’ does not name a type; did you mean ‘AVIOContext’?
  551 |     AVBSFContext* bsfc;
      |     ^~~~~~~~~~~~
      |     AVIOContext
/run/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp: In member function ‘void CvCapture_FFMPEG::init()’:
/run/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:598:5: error: ‘bsfc’ was not declared in this scope
  598 |     bsfc = NULL;
      |     ^~~~

This reverts commit a54348ce3dfbe5816333679b180764db78756b55.